import { NextResponse } from "next/server";

const CPV_CODES = [
	{ code: "03000000-1", label: "Landbouw- en veeteelt-, kwekerij-, visserij-, bosbouw- en aanverwante producten" },
	{ code: "09000000-3", label: "Aardolieproducten, brandstof, elektriciteit en andere energiebronnen" },
	{ code: "14000000-1", label: "Mijnbouw, basismetalen en aanverwante producten" },
	{ code: "15000000-8", label: "Voeding, dranken, tabak en aanverwante producten" },
	{ code: "16000000-5", label: "Landbouwmachines" },
	{ code: "18000000-9", label: "Kleding, schoeisel, bagageartikelen en accessoires" },
	{ code: "19000000-6", label: "Leder, textielweefsels, kunststof en rubber materialen" },
	{ code: "22000000-0", label: "Drukwerk en aanverwante producten" },
	{ code: "24000000-4", label: "Chemische producten" },
	{ code: "30000000-9", label: "Kantoormachines en gegevensverwerkende apparatuur, kantooruitrusting en -benodigdheden, uitgez. meubilair en softwarepakketten" },
	{ code: "31000000-6", label: "Elektrische machines, apparaten, uitrusting en verbruiksartikelen; verlichting" },
	{ code: "32000000-3", label: "Radio-, televisie-, communicatie-, telecommunicatietoestellen en aanverwante apparatuur" },
	{ code: "33000000-0", label: "Medische apparatuur, farmaceutische artikelen en artikelen voor lichaamsverzorging" },
	{ code: "34000000-7", label: "Vervoersmaterieel en bijbehorende producten" },
	{ code: "35000000-4", label: "Uitrusting voor veiligheid, brandweer, politie en leger" },
	{ code: "37000000-8", label: "Muziekinstrumenten, sportartikelen, spelletjes, speelgoed, handwerk, kunstartikelen en toebehoren" },
	{ code: "38000000-5", label: "Laboratoriuminstrumenten, optische en precisie-instrumenten (uitgezonderd brillen)" },
	{ code: "39000000-2", label: "Meubelen (m.i.v. kantoormeubelen), inrichtingsartikelen, huishoudelijke apparaten (uitgez. verlichting) en schoonmaakproducten" },
	{ code: "41000000-9", label: "Verzameld en gezuiverd water" },
	{ code: "42000000-6", label: "Bedrijfsmachines" },
	{ code: "43000000-3", label: "Machines voor de mijnbouw, steengroeven en voor de bouw" },
	{ code: "44000000-0", label: "Structuren en materialen voor de bouw; ondersteunende producten voor de bouw (uitgezonderd elektrische apparatuur)" },
	{ code: "45000000-7", label: "Bouwwerkzaamheden" },
	{ code: "48000000-8", label: "Software en informatiesystemen" },
	{ code: "50000000-5", label: "Reparatie- en onderhoudsdiensten" },
	{ code: "51000000-9", label: "Installatiediensten (uitgezonderd software)" },
	{ code: "55000000-0", label: "Diensten voor hotel, restaurant en detailhandel" },
	{ code: "60000000-8", label: "Vervoersdiensten (uitg. vervoer van afval)" },
	{ code: "63000000-9", label: "Ondersteunende en aanvullende vervoersdiensten; reisbureaudiensten" },
	{ code: "64000000-6", label: "Post- en telecommunicatiediensten" },
	{ code: "65000000-3", label: "Openbare voorzieningen" },
	{ code: "66000000-0", label: "Financiële en verzekeringsdiensten" },
	{ code: "70000000-1", label: "Makelaarsdiensten" },
	{ code: "71000000-8", label: "Dienstverlening op het gebied van architectuur, bouwkunde, civiele techniek en inspectie" },
	{ code: "72000000-5", label: "IT-diensten: adviezen, softwareontwikkeling, internet en ondersteuning" },
	{ code: "73000000-2", label: "Onderzoek en ontwikkeling, en aanverwante adviezen" },
	{ code: "75000000-6", label: "Diensten voor openbaar bestuur, defensie en sociale verzekering" },
	{ code: "76000000-3", label: "Diensten in verband met de olie- en gasindustrie" },
	{ code: "77000000-0", label: "Diensten voor land-, bos- en tuinbouw, aquicultuur en imkerij" },
	{ code: "79000000-4", label: "Zakelijke dienstverlening: juridisch, marketing, consulting, drukkerij en beveiliging" },
	{ code: "80000000-4", label: "Diensten voor onderwijs en opleiding" },
	{ code: "85000000-9", label: "Gezondheidszorg en maatschappelijk werk" },
	{ code: "90000000-7", label: "Diensten inzake afvalwater, afval, reiniging en milieu" },
	{ code: "92000000-1", label: "Cultuur-, sport- en recreatiediensten" },
	{ code: "98000000-3", label: "Overige gemeenschaps-, sociale en persoonlijke diensten" },
];

export async function GET() {
	return NextResponse.json(CPV_CODES);
}
